version: '3.8'

services:
  kbje-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./json-files:/app/json-files
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3 